local oc = require('caironoon.open-color')

return {
	dark = {
		black       = oc.black,
		bg0         = oc.gray[10],
		bg1         = oc.gray[9],
		bg2         = oc.gray[8],
		bg3         = oc.gray[7],
		bg_d        = oc.black,
		bg_blue     = oc.blue[5],
		bg_yellow   = oc.yellow[2],
		fg          = oc.gray[5],
		purple      = oc.grape[4],
		green       = oc.lime[4],
		orange      = oc.orange[4],
		blue        = oc.blue[4],
		yellow      = oc.yellow[4],
		cyan        = oc.cyan[4],
		red         = oc.red[4],
		grey        = oc.gray[7],
		light_grey  = oc.gray[6],
		dark_cyan   = oc.cyan[10],
		dark_red    = oc.red[10],
		dark_yellow = oc.yellow[10],
		dark_purple = oc.grape[10],
		diff_add    = oc.green[10],
		diff_delete = oc.red[10],
		diff_change = oc.blue[10],
		diff_text   = oc.gray[9],
	},
	light = {
		black       = oc.black,
		bg0         = oc.gray[1],
		bg1         = oc.gray[3],
		bg2         = oc.gray[4],
		bg3         = oc.gray[5],
		bg_d        = oc.gray[6],
		bg_blue     = oc.blue[4],
		bg_yellow   = oc.yellow[5],
		fg          = oc.black,
		purple      = oc.grape[10],
		green       = oc.green[10],
		orange      = oc.orange[10],
		blue        = oc.blue[10],
		yellow      = oc.yellow[10],
		cyan        = oc.cyan[10],
		red         = oc.red[10],
		grey        = oc.gray[8],
		light_grey  = oc.gray[7],
		dark_cyan   = oc.cyan[10],
		dark_red    = oc.red[10],
		dark_yellow = oc.yellow[10],
		dark_purple = oc.grape[10],
		diff_add    = oc.green[2],
		diff_delete = oc.red[2],
		diff_change = oc.blue[2],
		diff_text   = oc.gray[5],
	},

}
